name: Diff DBM test output
description: Runs DBM tests on two commits and pushes the resulting output into a repository to get a diff
branding:
  icon: book
  color: blue

inputs:
  dbm-offline-repo:
    default: DeadlyBossMods/DBM-Offline
  dbm-offline-ref:
    default: ""
  dbm-main-repo:
    default: DeadlyBossMods/DeadlyBossMods
  dbm-main-ref:
    default: ""
  dbm-main-base-ref:
    default: ""
  dbm-mod-repo-vanilla:
    default: "DeadlyBossMods/DBM-Vanilla"
  dbm-mod-ref-vanilla:
    default: ""
  dbm-mod-base-ref-vanilla:
    default: ""
  dbm-mod-repo-dungeons:
    default: "DeadlyBossMods/DBM-Dungeons"
  dbm-mod-ref-dungeons:
    default: ""
  dbm-mod-base-ref-dungeons:
    default: ""
  test-dbm-core-mods:
    default: false
  test-dbm-vanilla-mods:
    default: false
  test-dbm-dungeon-mods:
    default: false
  upload-repo:
    default: "DeadlyBossMods/DBM-Test-Results"
    required: true
  upload-repo-branch:
    required: true
  upload-token:
    required: true
  comment-token:
    required: false
  diff-mode:
    default: "true"

runs:
  using: composite
  steps:
    - name: Setup and DBM-Offline dependencies
      shell: bash
      run: |
        mkdir -p dbm-offline-diff
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get update
        sudo apt-get install -y lua5.1 luarocks subversion
        sudo luarocks --lua-version 5.1 install bitlib
        sudo luarocks --lua-version 5.1 install luafilesystem
    - name: Checkout DBM-Offline
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.dbm-offline-repo }}
        ref: ${{ inputs.dbm-offline-ref }}
        path: ./dbm-offline-diff/DBM-Offline
    - name: Checkout DBM main repo (New)
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.dbm-main-repo }}
        ref: ${{ inputs.dbm-main-ref }}
        path: ./dbm-offline-diff/DeadlyBossMods-new
    - name: Checkout DBM main repo (Base)
      if: ${{ inputs.diff-mode == 'true' }}
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.dbm-main-repo }}
        ref: ${{ inputs.dbm-main-base-ref }}
        path: ./dbm-offline-diff/DeadlyBossMods-base
    - name: Download DBM dependencies
      uses: BigWigsMods/packager@master
      with:
        args: -z -d -c -t ./dbm-offline-diff/DeadlyBossMods-new
    - name: Install DBM dependencies
      shell: bash
      run: |
        cp -r ./dbm-offline-diff/DeadlyBossMods-new/.release/DBM-Core/Libs ./dbm-offline-diff/DeadlyBossMods-new/DBM-Core/
        # FIXME: this is slightly incorrect and won't work if a dependency was removed
        cp -r ./dbm-offline-diff/DeadlyBossMods-new/.release/DBM-Core/Libs ./dbm-offline-diff/DeadlyBossMods-base/DBM-Core/ || true
    - name: Checkout DBM-Vanilla (New)
      uses: actions/checkout@v4
      if: ${{ inputs.test-dbm-vanilla-mods }}
      with:
        repository: ${{ inputs.dbm-mod-repo-vanilla }}
        ref: ${{ inputs.dbm-mod-ref-vanilla }}
        path: ./dbm-offline-diff/DBM-Vanilla-new
    - name: Checkout DBM-Vanilla (Base)
      uses: actions/checkout@v4
      if: ${{ inputs.test-dbm-vanilla-mods && inputs.diff-mode == 'true' }}
      with:
        repository: ${{ inputs.dbm-mod-repo-vanilla }}
        ref: ${{ inputs.dbm-mod-base-ref-vanilla }}
        path: ./dbm-offline-diff/DBM-Vanilla-base
    - name: Checkout DBM-Dungeons (New)
      uses: actions/checkout@v4
      if: ${{ inputs.test-dbm-dungeon-mods }}
      with:
        repository: ${{ inputs.dbm-mod-repo-dungeons }}
        ref: ${{ inputs.dbm-mod-ref-dungeons }}
        path: ./dbm-offline-diff/DBM-Dungeons-new
    - name: Checkout DBM-Dungeons (Base)
      uses: actions/checkout@v4
      if: ${{ inputs.test-dbm-dungeon-mods && inputs.diff-mode == 'true' }}
      with:
        repository: ${{ inputs.dbm-mod-repo-dungeons }}
        ref: ${{ inputs.dbm-mod-base-ref-dungeons }}
        path: ./dbm-offline-diff/DBM-Dungeons-base
    - name: Run tests (New)
      shell: bash
      run: |
        cd dbm-offline-diff/DBM-Offline
        for flavor in Retail SoD; do
          if [[ ${{ inputs.test-dbm-core-mods }} == true ]]; then
            lua5.1 main.lua --flavor $flavor --dbm ../DeadlyBossMods-new --mods ../DeadlyBossMods-new
          fi
          if [[ ${{ inputs.test-dbm-vanilla-mods }} == true ]]; then
            lua5.1 main.lua --flavor $flavor --dbm ../DeadlyBossMods-new --mods ../DBM-Vanilla-new
          fi
          if [[ ${{ inputs.test-dbm-dungeon-mods }} == true ]]; then
            lua5.1 main.lua --flavor $flavor --dbm ../DeadlyBossMods-new --mods ../DBM-Dungeons-new
          fi
        done
        mkdir -p ../results
        mv reports ../results/new
    - name: Run tests (Base)
      if: ${{ inputs.diff-mode == 'true' }}
      shell: bash
      run: |
        cd dbm-offline-diff/DBM-Offline
        for flavor in Retail SoD; do
          if [[ ${{ inputs.test-dbm-core-mods }} == true ]]; then
            lua5.1 main.lua --flavor $flavor --dbm ../DeadlyBossMods-base --mods ../DeadlyBossMods-base
          fi
          if [[ ${{ inputs.test-dbm-vanilla-mods }} == true ]]; then
            lua5.1 main.lua --flavor $flavor --dbm ../DeadlyBossMods-base --mods ../DBM-Vanilla-base
          fi
          if [[ ${{ inputs.test-dbm-dungeon-mods }} == true ]]; then
            lua5.1 main.lua --flavor $flavor --dbm ../DeadlyBossMods-base --mods ../DBM-Dungeons-base
          fi
        done
        mkdir -p ../results
        mv reports ../results/base
    - name: Upload diff
      id: upload
      if: ${{ inputs.diff-mode == 'true' }}
      shell: bash
      run: |
        cd dbm-offline-diff/DBM-Offline
        lua5.1 diff.lua ../results/base ../results/new > ../summary.txt
        cd ..
        mkdir upload-results
        cd upload-results
        git init .
        git config --global user.email "ci@deadlybossmods.com"
        git config --global user.name "DBM CI"
        git checkout -b ${{ inputs.upload-repo-branch }}
        mv ../results/base reports
        rm -f reports/.gitignore
        git add reports/*
        git commit --allow-empty -a -m "Base test results" \
          -m "Core: https://github.com/${{ inputs.dbm-main-repo }}/commit/${{ inputs.dbm-main-base-ref }}" \
          -m "Vanilla: https://github.com/${{ inputs.dbm-mod-repo-vanilla }}/commit/${{ inputs.dbm-mod-base-ref-vanilla }}" \
          -m "Dungeons: https://github.com/${{ inputs.dbm-mod-repo-dungeons }}/commit/${{ inputs.dbm-mod-base-ref-dungeons }}"
        rm -rf reports/
        mv ../results/new reports
        rm -f reports/.gitignore
        git add reports/*
        git commit --allow-empty -a -m "Test results" \
          -m "Core: https://github.com/${{ inputs.dbm-main-repo }}/commit/${{ inputs.dbm-main-ref }}" \
          -m "Vanilla: https://github.com/${{ inputs.dbm-mod-repo-vanilla }}/commit/${{ inputs.dbm-mod-ref-vanilla }}" \
          -m "Dungeons: https://github.com/${{ inputs.dbm-mod-repo-dungeons }}/commit/${{ inputs.dbm-mod-ref-dungeons }}"
        git push https://${gh_token}@github.com/${{ inputs.upload-repo }} ${{ inputs.upload-repo-branch }}
        sed -i "s|{{fullDiffLink}}|https://github.com/${{ inputs.upload-repo }}/commit/$(git rev-parse HEAD)|" ../summary.txt
        sed -i "s|{{fullResultsLink}}|https://github.com/${{ inputs.upload-repo }}/tree/$(git rev-parse HEAD^)/reports|" ../summary.txt
        echo 'diff<<EOFDelim' >> $GITHUB_OUTPUT
        cat ../summary.txt >> $GITHUB_OUTPUT
        echo EOFDelim >> $GITHUB_OUTPUT
        cat ../summary.txt >> $GITHUB_STEP_SUMMARY
      env:
        gh_token: ${{ inputs.upload-token }}
    - name: Upload test results
      if: ${{ inputs.diff-mode == 'false' }}
      shell: bash
      run: |
        cd dbm-offline-diff/
        git clone https://github.com/${{ inputs.upload-repo }} upload-results
        cd upload-results
        git checkout ${{ inputs.upload-repo-branch }}
        git config --global user.email "ci@deadlybossmods.com"
        git config --global user.name "DBM CI"
        mv ../results/new/* .
        git add *
        git commit --allow-empty -a -m "Test results" \
          -m "Core: https://github.com/${{ inputs.dbm-main-repo }}/commit/$(git -C ../DeadlyBossMods-new rev-parse HEAD)" \
          -m "Vanilla: https://github.com/${{ inputs.dbm-mod-repo-vanilla }}/commit/$(git -C ../DBM-Vanilla-new rev-parse HEAD)" \
          -m "Dungeons: https://github.com/${{ inputs.dbm-mod-repo-dungeons }}/commit/$(git -C ../DBM-Dungeons-new rev-parse HEAD)"
        git push https://${gh_token}@github.com/${{ inputs.upload-repo }} ${{ inputs.upload-repo-branch }}
      env:
        gh_token: ${{ inputs.upload-token }}
    - name: Cleanup
      shell: bash
      if: always()
      run: |
        # just making sure the auth token is definitely gone
        rm -rf dbm-offline-diff/upload-results/.git
    - name: Post comment
      uses: actions/github-script@v5
      if: ${{ github.event_name == 'pull_request' && inputs.diff-mode == 'true' }}
      with:
        github-token: ${{ inputs.comment-token }}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `${{ steps.upload.outputs.diff }}`
          })
